# .readthedocs.yaml

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"  # or any other version you need

python:
  install:
    - requirements: biasd/docs/requirements.txt
    - path: .

sphinx:
  configuration: biasd/docs/conf.py